name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  node-version: '16'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - run: npm ci
        name: Install dependencies
      - run: npm run build
        name: Build
      - run: npm test
        name: Unit tests
